### ISSUE TITLE
Will Placement support replicas scheduling?

### ISSUE THREAD

**Issue by ivan-cai** [open-cluster-management-io/placement#96]
for example, global replicas is 10, and 2 in cluster1, 3 in cluster2, 5 in cluster3 after scheduling.

**Comment by xuc623671** [comment]
This is a good idea, it is needed in actual use

**Comment by haoqing0110** [comment]
What's the expected input and output? Currently, the placementdecision only contains a list of cluster names.

**Comment by qiujian16** [comment]
@haoqing0110 would you help to move this issue to ocm repo. I am going to archive this repo.

**Comment by haoqing0110** [comment]
@qiujian16 yes, copied to https://github.com/open-cluster-management-io/ocm/issues/655 .
